begin;

-- Template for new Supabase-backed tables.
-- Replace <table_name> with the actual table name.
-- The helper below is only useful if your JWTs carry an integer user_id claim.

create or replace function public.app_user_id()
returns bigint
language sql
stable
as $$
  select nullif(
    coalesce(
      current_setting('request.jwt.claims', true)::jsonb ->> 'user_id',
      current_setting('request.jwt.claims', true)::jsonb ->> 'sub'
    ),
    ''
  )::bigint;
$$;

create table if not exists public.<table_name> (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public."user"(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.<table_name> enable row level security;

revoke all on table public.<table_name> from anon, authenticated, public;
grant select, insert, update, delete on table public.<table_name> to authenticated;
grant all on table public.<table_name> to service_role;

create policy "<table_name>_select_own"
on public.<table_name>
for select
to authenticated
using (user_id = public.app_user_id());

create policy "<table_name>_insert_own"
on public.<table_name>
for insert
to authenticated
with check (user_id = public.app_user_id());

create policy "<table_name>_update_own"
on public.<table_name>
for update
to authenticated
using (user_id = public.app_user_id())
with check (user_id = public.app_user_id());

create policy "<table_name>_delete_own"
on public.<table_name>
for delete
to authenticated
using (user_id = public.app_user_id());

-- Optional variant for a public lookup table:
-- grant select on table public.<table_name> to anon;
-- create policy "<table_name>_public_read"
-- on public.<table_name>
-- for select
-- to anon, authenticated
-- using (true);

commit;